
- name: Build and Run Docker Container
  hosts: remote
  become: true  # Optional: use this if you need elevated privileges to run Docker
  vars:
    remote_server_ip: "172.31.24.159"   # Example, replace with actual IP
    remote_server_user: "linux"          # Example, replace with actual user

  tasks:
    # Task 1: Build Docker Image
    - name: Build Docker Image
      docker_image:
        build:
          path: /root/dock/  # Path to the directory containing the Dockerfile
        name: nila_kavi
        tag: latest

    # Task 2: Run Docker Container
    - name: Run Docker container
      docker_container:
        name: nila_kavi_container
        image: nila_kavi:latest
        state: started
        restart_policy: always
        ports:
          - "2020:80"
        env:
          REMOTE_SERVER_IP: "{{ remote_server_ip }}"
          REMOTE_SERVER_USER: "{{ remote_server_user }}"
        volumes:
          - /home/ec2-user/.ssh/id_rsa:/root/.ssh/id_rsa  # Mount the SSH key into the container

