- name: copy module
  hosts: ansible
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/docker_file/Dockerfile
        dest: /home/ec2-user
        mode: '0644'


    - name: Copy file html
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/docker_file/html
        dest: /home/ec2-user
        mode: '0644'

    - name: Copy file nginx
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/docker_file/nginx.conf
        dest: /home/ec2-user
        mode: '0644'

    - name: Install docker
      ansible.builtin.command:
        cmd: yum update -y && yum install docker -y

        

    - name: start docker
      ansible.builtin.command:
        cmd: sudo systemctl enable docker

    - name: start dockers
      ansible.builtin.command:
        cmd: sudo systemctl start docker

    - name: permission
      ansible.builtin.command:
        cmd: chmod 777 /var/run/docker.sock

    - name: Run the Linux command
      ansible.builtin.command:
        cmd: docker build -t app .

    - name: remove previous container
      ansible.builtin.command:
        cmd: docker rm -f prakash

    - name: run docker 
      ansible.builtin.command:
        cmd: docker run -itd --name prakash -p 8083:8080 app


    - name: remove file
      ansible.builtin.command:
        cmd: rm -f /home/ec2-user/Dockerfile

    

    



